---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu and Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install updates (AlmaLinux and Fedora)
    tags: always
    dnf:
      name: "*"
      state: latest
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["AlmaLinux", "Fedora"]

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages (Ubuntu and Debian)
    tags: apache,apache2,ubuntu,debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 and php packages (AlmaLinux)
    tags: apache,almalinux,httpd
    dnf:  
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: start httpd (AlmaLinux)
    tags: apache,almalinux.https
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "AlmaLinux"

  - name: change e-mail address for admin
    tags: apache,almalinux,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin berg@infracom.nl
    when: ansible_distribution == "AlmaLinux"
    register: httpd

  - name: restart httpd (AlmaLinux)
    tags: apache,almalinux,httpd
    service: 
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu and Debian)
    tags: db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install mariadb package (AlmaLinux)
    tags: db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest
