---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu and Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install updates (AlmaLinux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages (Ubuntu and Debian)
    tags: apache,apache2,ubuntu,debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 and php packages (AlmaLinux)
    tags: apache,almalinux,httpd
    dnf:  
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu and Debian)
    tags: db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install mariadb package (AlmaLinux)
    tags: db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest
