- name: install apache2 and php packages (Ubuntu and Debian)
  tags: apache,apache2,ubuntu,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: install apache2 and php packages (AlmaLinux)
  tags: apache,almalinux,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "AlmaLinux"

- name: start httpd (AlmaLinux)
  tags: apache,almalinux.https
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "AlmaLinux"

- name: change e-mail address for admin
  tags: apache,almalinux,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin berg@infracom.nl
  when: ansible_distribution == "AlmaLinux"
  register: httpd

- name: restart httpd (AlmaLinux)
  tags: apache,almalinux,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644


